import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/?zx=1778714393601');
  await page.getByRole('combobox', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('why is play');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.getByRole('combobox', { name: 'Search' }).press('ArrowDown');
  await page.locator('iframe[name="a-c1ox456ibf8m"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').dblclick();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="0"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="1"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="5"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="4"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').dblclick();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-c1ox456ibf8m"]').contentFrame().getByRole('button', { name: 'Next' }).click();
});